config/routes.rb
Rails.application.routes.draw do
  root :to => 'artists#new'

  get 'artists/index'
end

app/models/artist.rb
class Artist
  def self.token
    client_id = Rails.application.secrets.client_id
    client_secret = Rails.application.secrets.client_secret

    api = Hyperclient.new('https://api.artsy.net/api') do |api|
      api.headers['Accept'] = 'application/vnd.artsy-v2+json'
      api.headers['Content-Type'] = 'application/json'
      api.connection(default: false) do |conn|
        conn.use FaradayMiddleware::FollowRedirects
        conn.use Faraday::Response::RaiseError
        conn.request :json
        conn.response :json, content_type: /\bjson$/
        conn.adapter :net_http
      end
    end
    api.tokens.xapp_token._post(client_id: client_id, client_secret: client_secret).token
  end

  def self.get param
    api = Hyperclient.new('https://api.artsy.net/api') do |api|
      api.headers['Accept'] = 'application/vnd.artsy-v2+json'
      api.headers['X-Xapp-Token'] = token
      api.connection(default: false) do |conn|
        conn.use FaradayMiddleware::FollowRedirects
        conn.use Faraday::Response::RaiseError
        conn.use Errors::RaiseError
        conn.request :json
        conn.response :json, content_type: /\bjson$/
        conn.adapter :net_http
      end
    end
    results = api.artist(id: "#{param.downcase.gsub ' ', '-'}")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Errors::RescueError
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  after_action :lumberjack, only: :index
  before_action :start_time, only: :index

  def index
    @artist = Artist.get(params[:search])
    respond_to do |format|
      format.js
    end
  end

  def new
  end

  def lumberjack
    Lumberjack.save params[:search], request.ip, @artist._links.count, end_time
  end

  def start_time
    @time = Time.now
  end

  def end_time
    Time.now - @time
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/artists/_index.html.erb
<div id='artist'>
  <%= @artist.name %>
  </br>
  <%= image_tag @artist.thumbnail %>
</div>

app/views/artists/index.js.erb
$('#artist').replaceWith("<%= j (render 'artists/index') %>");

app/views/artists/new.html.erb
<%= render 'layouts/search' %>

app/views/layouts/_search.html.erb
<%= form_tag artists_index_path, remote: true, method: :get do %>
  <p>
    <%= text_field_tag :search, params[:query] %>
    <%= submit_tag 'Search', name: nil %>
  </p>
<% end %>

<div id='artist'></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Artsy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>